### PR TITLE
Bump version to 0.4.1, add in 9.1.0 support

### PR DESCRIPTION
**Pull request by borntohonk**

### CODE REVIEW

**Comment by Chippel** [comment]
This may be a stupid question but where's the file?

**Comment by V33m** [comment]
@Chippel - Latest release from the [borntohonk/Incognito_RCM fork](https://github.com/borntohonk/Incognito_RCM/releases/latest).

**Comment by ELY3M** [comment]
great!  I did same thing few days ago.

**Comment by ELY3M** [comment]
it is in pkg1.c in the hos folder.

**Comment by borntohonk** [comment]
@ELY3M I did it 5 days ago, you did it 2 days ago. 🤷‍♂

**Comment by jimzrt** [comment]
thanks!

**Comment by borntohonk** [comment]
remember to compile / add a binary pls @jimzrt

**Pull request merged**
